name: Backend CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3
        
      - uses: actions/checkout@v3
      - run: mkdir ./src/main/resources
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
      - uses: actions/upload-artifact@v2
        with:
          name: application.yml
          path: ./src/main/resources/application.yml
        

      - name: 스프링부트 애플리케이션 빌드
        run: ./gradlew build -x test

      - name: 도커 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_IMG }} .
        
      - name: 도커 이미지 푸시
        run: docker push ${{ secrets.DOCKER_IMG }} 
        
      - name: 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          password: ${{ secrets.WAS_PASSWORD }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            docker pull ${{ secrets.DOCKER_IMG }}
            docker run -d -p 8080:8080 ${{ secrets.DOCKER_IMG }}
